### PR TITLE
Introduce parent pom for ITs

### PR DESCRIPTION
**Pull request by pzygielo**
I propose to introduce new pom (`src/it/modules/pom.xml`), that all IT modules would be children of. This parent may collect all common settings, leaving for modules to configure tested `spec-version-maven-plugin` only.

### CODE REVIEW

**Comment by arjantijms** [comment]
LGTM, thx!

**Comment by romain-grecourt** [comment]
Please use the squash option when merging. The history is messed-up now.

**Comment by pzygielo** [comment]
> Please use the squash option when merging. The history is messed-up now.

I do not agree. The history now is complete. How do you check history to have impression of it being messed-up? I'm using CLI and git's version tree is beaten only by ClearCase IMO.

**Comment by romain-grecourt** [comment]
It's a good practice to squash PRs as a single commit: 1 PR -> 1 commit -> 1 issue.
That also enables simple revert and cherry-pick.

The intermediate commits are in most cases not relevant to retain.
See below, these individual commits have no value on their own.

```
* |   f92ae1a  Merge pull request #25 from pzygielo/it-parent
|\ \  
| |/  
|/|   
| * 42202f2  Manage execution in parent
| * 0498d13  Use filtered version
| * 8ad7a07  Use m-bundle-p in parent, remove from children
| * 3aef590  Remove configuration that is managed in parent
| * f6f3eea  Manage m-bundle-p for IT modules
| * f8bbb26  Remove m-jar-p, that is managed in parent
| * cc99b2b  Manage m-jar-p for IT modules
| * 57a05a0  Remove m-surefire-p, that is managed in parent
| * 72180ed  Manage m-surefire-p for IT modules
| * 71718a2  Remove common properties set in parent
| * ba678e1  Let all IT modules have the same parent
| * 04537e2  Introduce parent pom for IT modules
|/  
```

**Comment by bshannon** [comment]
I agree with Romain, please use squash!

**Comment by pzygielo** [comment]
> I agree with Romain, please use squash!

That is recommendation for merging operation only, right?

**Comment by romain-grecourt** [comment]
Yes.

**Pull request merged**
